version: '3.4'

services:
    account:
        image: 'account:latest'
        ports:
            - '32773:80'
        build:
            context: .
            dockerfile: Account/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            # valid options for TracingOptions__TracerTarget : datadog , jaeger
            # if you chhose jaeger, you must set DD_TRACE_ENABLED=true, or even better CORECLR_ENABLE_PROFILING=0 to disable datadog auto tracing (APM)
            # automatic tracing will be sent to datadog
            - TracingOptions__TracerTarget=datadog
            #read for jaeger only. for dd we leverge apm using DD_TRACE_ENABLED=true
            - TracingOptions__EnableOpenTracingAutoTracing=false

            # jaeger
            - JAEGER_SERVICE_NAME=Account
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
            - JAEGER_SAMPLER_TYPE=const
            - JAEGER_SAMPLER_PARAM=1
            - JAEGER_REPORTER_LOG_SPANS=true

            #datadog
            # system env variables (required to activate any profiler)
            # the id of the datadog profiler, required for APM (Automatic tracing)
            - CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
            # the path of the datadog profiler, required for APM (Automatic tracing)
            - CORECLR_PROFILER_PATH_64=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
            #enable the profiler
            - CORECLR_ENABLE_PROFILING=1
            # datadog specific env vars
            # enable datadog profiler
            - DD_TRACE_ENABLED=true
            - DD_INTEGRATIONS=/opt/datadog/integrations.json
            - DD_DOTNET_TRACER_HOME=/opt/datadog
            - DD_TRACE_ANALYTICS_ENABLED=true
            # inject traceid in the the logs, for correlation
            - DD_LOGS_INJECTION=true
            - DD_INTEGRATIONS_ENABLED=true
            # enable logs for profiler / dd tracer. REMOVE IN PRD
            - DD_TRACE_DEBUG=true
            # the name of the agent to send traces
            - DD_AGENT_HOST=datadog
            # properties to tag traces
            - DD_ENV=playground
            - DD_SERVICE_NAME=Account

        networks:
            - trace-example-network
        depends_on:
            - jaeger
            - datadog

    jaeger:
        image: 'jaegertracing/all-in-one:latest'
        command: --log-level=debug
        expose:
            - '5775/udp'
            - '6831/udp'
            - '6832/udp'
            - '5778'
            - '14268'
            - '9411'
        ports:
            #to expose the jeager ui
            - '16686:16686'
        environment:
            - 'COLLECTOR_ZIPKIN_HTTP_PORT=9411'
        networks:
            - trace-example-network
    datadog:
        image: datadog/agent:7
        networks:
            - trace-example-network
        environment:
            - DD_API_KEY=<..>
            # listen to apm traces send by APM
            - DD_APM_ENABLED=true
            # accept APM traces from other running hosts / containers
            - DD_APM_NON_LOCAL_TRAFFIC=true
              # enable logs for agent. REMOVE IN PRD
            - DD_LOG_LEVEL=debug
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
networks:
    trace-example-network:
