version: '3.3'

services:
    wharehouse-producer:
        image: 'producer:latest'
        build:
            context: .
            dockerfile: producer/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - RABBIT_HOST=rabbitmq
            # jaeger
            - JAEGER_SERVICE_NAME=wharehouse-producer
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
            - JAEGER_SAMPLER_TYPE=const
            - JAEGER_SAMPLER_PARAM=1
            - JAEGER_REPORTER_LOG_SPANS=true
        restart: on-failure
        depends_on:
            - rabbitmq
        networks:
            - wharehouse-network

    wharehouse-consumer:
        image: 'consumer:latest'
        build:
            context: .
            dockerfile: consumer/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - RABBIT_HOST=rabbitmq
            # jaeger
            - JAEGER_SERVICE_NAME=wharehouse-consumer
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
            - JAEGER_SAMPLER_TYPE=const
            - JAEGER_SAMPLER_PARAM=1
            - JAEGER_REPORTER_LOG_SPANS=true
            #- ITEMS_URL=http://localhost:3001/item
        restart: on-failure
        depends_on:
            - rabbitmq
        networks:
            - wharehouse-network
   
    rabbitmq:
        image: 'rabbitmq:3-management'
        expose:
          - 5672
          - 15672
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - wharehouse-network
        healthcheck:
          test: [ "CMD", "nc", "-z", "localhost", "5672" ]
          interval: 10s
          timeout: 15s
          retries: 10
    jaeger:
        image: 'jaegertracing/all-in-one:latest'
        command: --log-level=debug
        expose:
            - '5775/udp'
            - '6831/udp'
            - '6832/udp'
            - '5778'
            - '14268'
            - '9411'
        ports:
            #to expose the jeager ui
            - '16686:16686'
        environment:
            - 'COLLECTOR_ZIPKIN_HTTP_PORT=9411'
        networks:
            - wharehouse-network
networks:
    wharehouse-network:
